<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'timeline.title' => '¡Feliz cumpleaños {username}!',
    'timelime.main.message' => 'Hoy es un gran día para ti y queremos felicitarte de una manera diferente.<br>Cuando yo cumplí 30 años me hiciste regalo que nunca olvidaré y quiero devolverte la gran experiencia
    que tuve.<br>Eres una persona muy especial y muy querida por mucha gente, que no ha dudado en felicitarte de una manera original y personal.<br>Espero que las disfrutes y que tengas una nueva decada llena de grandes aventuras, deseos cumplidos y momentos felices.
    <br> ¡Qué sigamos cumpliendo años juntos! Te quiero :*, Jesús.',
    'timeline.como.funciona' => '<h1>¿Cómo funciona?</h1><br>Cada tarjeta que ves es una felicitación personal formada por cinco páginas, simplemente clica sobre ellas para pasa de página y disfrútalas.',
];
