<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activar' => '',
    'Are you sure you want to delete this item?' => '',
    'Borrar' => '',
    'Color' => '',
    'Consejo' => '',
    'Contact' => '',
    'Create Post' => '',
    'Created At' => '',
    'Created By' => '',
    'Delete' => '',
    'Description' => '',
    'Extension' => '',
    'Felicitación' => '',
    'Fichero ID' => '',
    'Hola Mundo!!' => '',
    'Lang' => '',
    'Nombre' => '',
    'Post ID' => '',
    'Posts' => '',
    'Qué es' => '',
    'Reset' => '',
    'Ruta' => '',
    'Ruta Completa' => '',
    'Save' => '',
    'Search' => '',
    'Size' => '',
    'Status' => '',
    'Tabla Padre' => '',
    'Tabla Padre ID' => '',
    'Tarjeta pública' => '',
    'Tarjetas' => '',
    'Test Desc' => '',
    'Test ID' => '',
    'Title' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Ver {total} {foto}' => '',
    'boton.enviar' => '',
    'flash.message.' => '',
    'flash.title.' => '',
    'foto' => '',
    'fotos' => '',
    'site.about' => '',
    'site.contact' => '',
    'timeline.users.welcome' => '',
    '¿Qué es para mí Danielle?' => '',
    '¿Un consejo para esta nueva decada?' => '',
    'adios-mundo' => '@@@@',
    'flash.message.danger' => '@@Algo ha salido mal...@@',
    'flash.message.success' => '@@Operacion realizada correctamente@@',
    'flash.title.danger' => '@@Ups!@@',
    'flash.title.success' => '@@Gracias@@',
    'general-aceptar' => '@@@@',
    'general-bienvenido' => '@@@@',
    'general-cargando' => '@@@@',
    'general-politica-cookies' => '@@@@',
    'hola-mundo' => '@@@@',
    'timeline.users.wellcome' => '@@¡Hola {username}!@@',
    'cake.days' => 'D.',
    'cake.months' => 'M.',
    'cake.weeks' => 'S.',
    'noscript.message' => 'JavaScript debe estar habilitado para que la página funcione correctamente.',
    'post.cambiar-portada' => 'Elegir otra imagen',
    'post.crear.tarjeta' => 'Crear tarjeta de cumpleaños',
    'post.info.con-tarjeta' => 'Hola {username}, esta es la tarjeta que has creado. Puedes modificarla cuando quieras.',
    'post.info.sin-tarjeta' => 'Hola {username}, gracias por llegar hasta aquí, ahora sólo queda crear tu tarjeta molona para Danielle.',
    'post.modificar.tarjeta' => 'Modificar la tarjeta',
    'post.sin-tarjeta' => 'Aún no has creado tu tarjeta',
    'site.como-funciona.question' => 'Sí, muy bonito pero... ¿Cómo se hace?',
    'site.como-funciona.question-answer' => 'Sólo sigue estos pasos',
    'site.como-funciona.question-answer.1' => 'Esta web es privada y tiene un control de acceso, así que es necesario que primero os registréis (SignUp),
    con un nombre de usuario, email* y contraseña es suficiente. <p class="text-grey-light" style="font-size:small">*Se mandará un email de confirmación para completar el registro, poned un email que utilicéis a menudo.</p>',
    'site.como-funciona.question-answer.2' => 'Una vez registrados ya podéis escribir a Danielle clicando donde ponga \'Crear tarjeta\'',
    'site.como-funciona.question-answer.3' => 'Et voilà! Habréis hecho a una gran persona un poquito más feliz, ¡Gracias!.',
    'site.como-funciona.question-answer.4' => 'Para registrarte y felicitar a Danielle clica en el sobre.',
    'site.index.welcome' => '¡Welcome to Danielle\'s 30th Birthday!',
    'site.thanks' => '<h1 class="question">Thank you very much for being here</h1><h3>Please, take a couple of minutes to read the following</h3><br>
Danielle is turning 30 years old this year, ans since she is such a good girl (most of the times), I would like you guys to dedicate her something special, so she can get a nice surprise on her birthday,
specially from beloved people that is so far in her everyday life.',
    'site.thanks.2' => 'La idea es sencilla, a través de esta web le creamos una tarjeta de cumpleaños, para que cuando las vea, se le caiga la lagrimita...',
    'site.thanks.2.1' => 'Las tarjetas de cumpleaños podrán ser privadas o públicas,
        vosotros decidiréis si sólo queréis que la vea Dani, o que el día de su cumple pueda verla otros usuarios de la web.',
    'site.thanks.3' => 'El día de su cumpleaños (hasta entonces ella no tiene ni idea de nada claro), accederá a la web con su usuario propio y verás todas las tarjetas de cumpleaños con vuestros bonitos mensajes y recuerdos.',
    'site.thanks.4' => 'Aquí podéis ver un ejemplo de lo que os pido que hagáis, es muy sencillo ya veréis y vosotros podréis customizar la vuestra, esta es la que nuestro gatito McFly le ha creado:',
    'site.time.left' => 'Time left...',
    'sobre.escribir' => '¡Felicitar a Danielle!',
];
