<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'timeline.title' => 'Happy Birthday {username}!',
    'timelime.main.message' => '
Today is a great day for you and we want to congratulate you in a different way.<br>When I turned 30, you made me a gift that I will never forget and I want to give you back the great experience
I had.<br> You are a very special person and you are loved by many people, who have not hesitated in congratulating you in an original and personal way.<br> I hope you enjoy them and have a new decade filled with great adventures, fulfilled desires and happy moments.
<br> May we continue to celebrate together as many years we turn into! Love you :*, Jesus.',
    'timeline.como.funciona' => '<h1>¿How does it work?</h1><br>Each card is a personal birthday card with five pages. Just click on them to see the next page and enjoy them.',
];
